/**
 * Baked official circuit geometry from the MultiViewer circuit API.
 *
 * Files in src/data/circuit-geometry/*.json are generated by:
 *   node scripts/fetch-circuits.mjs
 *
 * The x[], y[] coordinates are in the same F1 Cartesian space as the OpenF1
 * /location endpoint — no transform needed to overlay car positions.
 */
import type { CircuitGeometry } from "./circuitGeometryTypes";

// Lazy glob: each JSON file becomes its own chunk, so a session only downloads
// the geometry for its own circuit instead of every circuit (~2.4 MB).
// Returns {} when the directory is empty (before running the bake script),
// which causes useTrackOutline to fall back to the GPS-derived path.
const loaders = import.meta.glob<CircuitGeometry>("./circuit-geometry/*.json", {
  import: "default",
});

type GeometryLoader = () => Promise<CircuitGeometry>;

// Map: circuit_key → (year → loader). Built from file names only.
const CIRCUIT_GEOMETRY = new Map<number, Map<number, GeometryLoader>>();
for (const [path, loader] of Object.entries(loaders)) {
  // Filenames are "{circuitKey}-{year}.json"
  const m = path.match(/\/(\d+)-(\d+)\.json$/);
  if (!m) continue;
  const circuitKey = Number(m[1]);
  const year = Number(m[2]);
  let yearMap = CIRCUIT_GEOMETRY.get(circuitKey);
  if (!yearMap) {
    yearMap = new Map();
    CIRCUIT_GEOMETRY.set(circuitKey, yearMap);
  }
  yearMap.set(year, loader);
}

const loaded = new Map<string, CircuitGeometry>();
const inFlight = new Map<string, Promise<CircuitGeometry | null>>();

const cacheKey = (circuitKey: number, year: number) => `${circuitKey}-${year}`;

/**
 * Resolves which baked year to use for a given circuit key and year.
 *
 * Lookup order:
 * 1. Exact year match.
 * 2. Nearest year ≤ requested (most-recent earlier layout).
 * 3. Nearest year overall (future-only data, e.g. brand-new circuit).
 */
function resolveGeometryYear(
  circuitKey: number,
  year?: number | null,
): number | null {
  const yearMap = CIRCUIT_GEOMETRY.get(circuitKey);
  if (!yearMap) return null;

  const availableYears = [...yearMap.keys()].sort((a, b) => a - b);
  if (availableYears.length === 0) return null;

  if (year == null) {
    // No year specified — use latest available
    return availableYears[availableYears.length - 1]!;
  }

  // Exact match
  if (yearMap.has(year)) return year;

  // Most recent year that is ≤ requested (correct historical layout)
  let best: number | null = null;
  for (const y of availableYears) {
    if (y <= year) best = y;
  }
  if (best !== null) return best;

  // Fallback: oldest available year (circuit only has future data)
  return availableYears[0]!;
}

/** True when baked geometry exists for the circuit (loaded or not). */
export function hasCircuitGeometry(
  circuitKey: number,
  year?: number | null,
): boolean {
  return resolveGeometryYear(circuitKey, year) !== null;
}

/**
 * Returns the baked geometry for a given circuit key and year if it has
 * already been loaded via `loadCircuitGeometry` (see `useCircuitGeometry`),
 * otherwise null.
 */
export function getCircuitGeometry(
  circuitKey: number,
  year?: number | null,
): CircuitGeometry | null {
  const resolvedYear = resolveGeometryYear(circuitKey, year);
  if (resolvedYear === null) return null;
  return loaded.get(cacheKey(circuitKey, resolvedYear)) ?? null;
}

/** Loads (and caches) the baked geometry for a given circuit key and year. */
export function loadCircuitGeometry(
  circuitKey: number,
  year?: number | null,
): Promise<CircuitGeometry | null> {
  const resolvedYear = resolveGeometryYear(circuitKey, year);
  if (resolvedYear === null) return Promise.resolve(null);

  const key = cacheKey(circuitKey, resolvedYear);
  const cached = loaded.get(key);
  if (cached) return Promise.resolve(cached);

  const pending = inFlight.get(key);
  if (pending) return pending;

  const loader = CIRCUIT_GEOMETRY.get(circuitKey)!.get(resolvedYear)!;
  const promise = loader()
    .then((geometry) => {
      loaded.set(key, geometry);
      return geometry;
    })
    .finally(() => {
      inFlight.delete(key);
    });
  inFlight.set(key, promise);
  return promise;
}

export type {
  CircuitGeometry,
  CornerInfo,
  MarshalSector,
  MarshalLight,
  PitLoss,
} from "./circuitGeometryTypes";
