/**
 * Baked official circuit geometry from the MultiViewer circuit API.
 *
 * Files in src/data/circuit-geometry/*.json are generated by:
 *   node scripts/fetch-circuits.mjs
 *
 * The x[], y[] coordinates are in the same F1 Cartesian space as the OpenF1
 * /location endpoint — no transform needed to overlay car positions.
 */
import type { CircuitGeometry } from './circuitGeometryTypes'

// Vite eager glob — loads all JSON files in the directory at build time.
// Returns {} when the directory is empty (before running the bake script),
// which causes useTrackOutline to fall back to the GPS-derived path.
const modules = import.meta.glob<CircuitGeometry>(
  './circuit-geometry/*.json',
  { eager: true, import: 'default' },
)

const CIRCUIT_GEOMETRY = new Map<number, CircuitGeometry>()
for (const [path, data] of Object.entries(modules)) {
  const m = path.match(/\/(\d+)\.json$/)
  if (m) CIRCUIT_GEOMETRY.set(Number(m[1]), data)
}

export function getCircuitGeometry(circuitKey: number): CircuitGeometry | null {
  return CIRCUIT_GEOMETRY.get(circuitKey) ?? null
}

export type { CircuitGeometry, CornerInfo, MarshalSector, MarshalLight } from './circuitGeometryTypes'
